### ISSUE TITLE
mcp.settings not working, throw error "AttributeError: 'FastMCP' object has no attribute 'settings'"

### ISSUE THREAD

**Issue by pointhalo** [PrefectHQ/fastmcp#798]
### Description

1. when i try to read settings.port、settings.host like [offical docs](https://gofastmcp.com/servers/fastmcp#server-configuration)

There will be attribute errors
```
print(mcp.settings.port)
          ^^^^^^^^^^^^
AttributeError: 'FastMCP' object has no attribute 'settings'
```

2. same code can work in v2.3.3, when i update to v2.8.0, encounter this error

### Example Code

```Python
from fastmcp import FastMCP

mcp = FastMCP(
    name="test",
)

print(mcp.settings.port)
```

### Version Information

```Text
/
```

**Comment by jlowin** [comment]
Thanks for catching - this access was meant to be deprecated not removed. Will add back asap.
