### ISSUE TITLE
caching middleware broken

### ISSUE THREAD

**Issue by gmenziesint** [PrefectHQ/fastmcp#4300]
### What happened?

After upgrading to v3.4.0+, any request that hits a cache miss in the caching middleware crashes with:

`TypeError: FastMCP._run_middleware.<locals>.wrapped() got an unexpected keyword argument 'context'`

Reproduction

1. Install fastmcp>=3.4.0 (tested on 3.4.2)
2. Create a server with any tool registered using caching
3. Connect a client and call tools/list

Cause
In v3.4.0, _run_middleware in server.py was refactored from functools.partial to an explicit closure:

```
async def wrapped(
    ctx: MiddlewareContext[Any],  # parameter named "ctx"
    mw: Middleware = mw,
    call_next: CallNext[Any, Any] = next_chain,
) -> Any:
    return await mw(ctx, call_next)
```

The caching.py middleware calls call_next using a keyword argument:

`tools: Sequence[Tool] = await call_next(context=context)`

Since the closure's parameter is named ctx (not context), the keyword doesn't match and Python raises a TypeError.

All other built-in middlewares pass e.g. rate_limiting, logging etc pass context positionally and are unaffected.

### Example Code

```Python

```

### Version Information

```Text
FastMCP version:                                                              3.4.2
MCP version:                                                                 1.27.2
Python version:                                                             3.12.13
Platform:              Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
FastMCP root path: /home/REDACTED/REDACTED/.venv/lib/python3.12/site-packages
```

**Comment by gmenziesint** [comment]
Hi. I've opened a PR with a fix for this #4301 , could a maintainer assign this to me so I can proceed :) Thanks

**Comment by gmenziesint** [comment]
Hoping someone can look at this soon as we're unable to update without it :)

**Comment by jlowin** [comment]
Thanks for catching!
